# Generated by Django 4.0.6 on 2022-09-02 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_alter_contactpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineaccount",
            name="icon",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[django.core.validators.RegexValidator("[a-z-\\\\s]")],
            ),
        ),
    ]
