# Generated by Django 4.0.6 on 2022-09-02 07:38

import fontawesome_6.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0006_alter_contactpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineaccount",
            name="icon",
            field=fontawesome_6.fields.IconField(blank=True, max_length=60),
        ),
    ]
