version: '3.7'
services:
  web:
    build:
      context: ../../
      target: dev
    init: true
    environment:
      - QUEUE_STORE_URL=redis://redis/0
      - DEBUG=true
      - SECRET_KEY=super-secret-key
      - DATABASE_URL=postgres://website:website@db/website
    volumes:
      - ../../:/app
    depends_on:
      - redis
      - db
    ports:
      - 127.0.0.1:8000:8000

  redis:
    image: redis:6.0

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=website
      - POSTGRES_USER=website
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
