[tool.djlint]
ignore = "T003,H006,H023,H030,H031"
indent = 2
preserve_blank_lines = true
profile = "django"
max_line_length = 12000
max_attribute_length = 1000
extension = "html"
format_attribute_template_tags=true
custom_blocks="cache"

[tool.djlint.per-file-ignores]
"_snippet_link.html" = "H025"

[tool.mypy]
no_implicit_optional = true
warn_unused_ignores = true
strict_optional = true
check_untyped_defs = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
exclude = [
  '^docker/dev/volumes',
  '^env'
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if settings.DEBUG"
]
omit = [
  "*/migrations/*",
]

[tool.ruff]
select = ["E", "F", "I", "W", "N", "B", "A", "C4", "T20", "DJ"]
ignore = ["E501", "DJ008"]

[tool.ruff.per-file-ignores]
"*/migrations/*" = ["N806"]
