[tool.djlint]
ignore = "T003,H006,H023,H030,H031"
indent = 2
preserve_blank_lines = true
profile = "django"
max_line_length = 12000
max_attribute_length = 1000
extension = "html"
format_attribute_template_tags=true
custom_blocks="cache"

[tool.djlint.per-file-ignores]
"_snippet_link.html" = "H025"
