# Generated by Django 4.0.5 on 2022-06-15 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="hero_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailimages.image",
            ),
        ),
    ]
