# Generated by Django 4.0.10 on 2023-04-16 13:49

import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_contentpage_body_alter_listingpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footersetting",
            name="icons",
            field=wagtail.fields.StreamField(
                [
                    (
                        "icon",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            "contact.OnlineAccount", icon="user"
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
