# Generated by Django 4.0.10 on 2023-04-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_footersetting_icons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersetting",
            name="site",
        ),
    ]
