# Generated by Django 4.0.5 on 2022-06-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "__first__"),
        ("common", "0007_alter_contentpage_body_alter_listingpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="listingpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="images.customimage",
            ),
        ),
    ]
