# Generated by Django 4.0.5 on 2022-07-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_referrallink_alter_contentpage_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("url", models.URLField()),
                ("username", models.CharField(max_length=64)),
            ],
        ),
    ]
