# Generated by Django 4.0.5 on 2022-07-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_alter_contentpage_body_alter_listingpage_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OnlineAccount",
        ),
    ]
