# Generated by Django 4.0.6 on 2022-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_alter_contentpage_body_alter_listingpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listingpage",
            name="subtitle",
        ),
    ]
