# Generated by Django 4.0.6 on 2022-09-02 08:14

import django.db.models.deletion
import wagtail.fields
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("common", "0021_alter_contentpage_body_alter_listingpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icons",
                    wagtail.fields.StreamField(
                        [
                            (
                                "icon",
                                wagtail.snippets.blocks.SnippetChooserBlock(
                                    "contact.OnlineAccount", icon="user"
                                ),
                            )
                        ],
                        use_json_field=None,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
            },
        ),
    ]
