# Generated by Django 4.0.6 on 2022-08-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifyplaylistpage",
            name="subtitle",
        ),
    ]
