# Generated by Django 4.0.5 on 2022-07-12 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unsplash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unsplashphoto",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unsplashphoto",
            name="data_last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
