# Generated by Django 4.0.5 on 2022-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="heading",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
