# Generated by Django 4.0.6 on 2022-09-03 15:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_alter_searchpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchpage",
            name="subtitle",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
