# Generated by Django 4.0.5 on 2022-06-19 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogposttag_taggedblog_blogpostpage_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
