# Generated by Django 5.0.4 on 2024-05-29 21:10

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_auto_20230602_1236"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalBlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("external_url", models.URLField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "tags",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="blog.blogposttagpage"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", wagtailmetadata.models.MetadataMixin),
        ),
    ]
