# Generated by Django 4.0.5 on 2022-07-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unsplash", "0001_initial"),
        ("blog", "0009_alter_bloglistpage_body_alter_blogpostpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloglistpage",
            name="hero_unsplash_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="unsplash.unsplashphoto",
            ),
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="hero_unsplash_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="unsplash.unsplashphoto",
            ),
        ),
    ]
