# Generated by Django 4.0.5 on 2022-07-16 08:37

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_blogposttaglistpage_blogposttagpage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="tags",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="blog.blogposttagpage"
            ),
        ),
    ]
