# Generated by Django 4.0.6 on 2022-08-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unsplash", "0002_unsplashphoto_created_and_more"),
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("images", "0001_initial"),
        ("blog", "0018_alter_blogcollectionlistpage_body_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogCollectionListPage",
            new_name="BlogPostCollectionListPage",
        ),
        migrations.RenameModel(
            old_name="BlogCollectionPage",
            new_name="BlogPostCollectionPage",
        ),
        migrations.RenameModel(
            old_name="BlogListPage",
            new_name="BlogPostListPage",
        ),
    ]
