# Generated by Django 4.0.6 on 2022-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_alter_blogpostcollectionlistpage_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostcollectionlistpage",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="blogpostcollectionpage",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="blogpostlistpage",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="blogposttaglistpage",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="blogposttagpage",
            name="subtitle",
        ),
    ]
