# Generated by Django 4.0.6 on 2022-09-03 15:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_blogpostcollectionlistpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="subtitle",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
